### ISSUE TITLE
Feature Suggestion: Explodes and Keep combination

### ISSUE THREAD

**Issue by lancerusso** [fponticelli/diceroller#35]
Systems such as L5R 4e use the _Roll and Keep_ system but with exploding dice for very dynamic rolls and notoriously deadly attacks.

Would be nice to be able to roll with explodes and keep the highest dice but this doesn't seem to be supported.

**Comment by fponticelli** [comment]
See issue #36 for a suggestion on how to do it. Thank you for the suggestion!
